blog_app/config/routes.rb
 Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'index' => 'blog#index' 
  get 'index/:id' => 'blog#show'
  get 'index/new' => 'blog#new', as: 'new_blog'
  post 'index' => 'blog#create'
end

blog_app/app/models/post.rb
class Post < ApplicationRecord
end

blog_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

blog_app/app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @index = Post.all
    end


    
    # def index
    #     render html:"this is a test"
    # end

    def show
        @blog = Post.find(params[:id])
    end

    def new
    end

    def create
        @blog = Post.create(
            title: params[:title],
            content: params[:content]
        )
        if @blog.valid?
            redirect_to index_path
        else
            redirect_to new_index_path
        end
    end
end

blog_app/app/helpers/blog_helper.rb
module BlogHelper
end

blog_app/app/views/blog/index.html.erb
<h1>Blog Application</h1>
<p> <%= link_to 'New Blog', new_blog_path %> </p>
<ol>
    <% @index.each do |index|  %>
        <li>
            <%= index.title %>
        </li>
        
    <% end %>
</ol>

blog_app/app/views/blog/new.html.erb
<h3>Add a new blog</h3>
<%= form_with url: '/index', local: true do |form| %>

    <%= form.label :title %>
    <%= form.text_field :title %>

    <br>
    <%= form.label :content %>
    <%= form.text_field :content %>

    <br>
    <%= form.submit 'Add Blog' %>
<% end %>

blog_app/app/views/blog/show.html.erb
<h3><%= @blog.title %></h3>
<p><%= @blog.content %></p>

blog_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>